---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Run OS-specific setup
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install required System Packages
  package:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ borg_packages }}"

- name: Update setuptools if needed
  tags: skip_ansible_lint
  pip:
    name: setuptools
    state: latest
    executable: "{{ pip_bin }}"

- name: Install required Python Packages
  pip:
    name: "{{ borg_python_packages }}"
    executable: "{{ pip_bin }}"

#- name: Ensure root has SSH key.
#  user:
#    name: "root"
#    generate_ssh_key: yes
#    ssh_key_file: "{{ ssh_key_file }}"
#    ssh_key_type: ed25519
#  register: root_user

#- debug:
#    var: root_user['ssh_public_key']


- name: Ensures borgmatic configuration directory exists
  file:
    path: "{{ borgmatic_config_dir }}"
    state: directory
    mode: 0700
    owner: root

- name: Add Borgmatic Configuration
  template:
    src: config.yaml.j2
    dest: "{{ borgmatic_config_dir }}/{{ borgmatic_config_name }}"
    mode: 0600

- name: Add cron-job for borgmatic (large repo, create and check separate)
  tags: molecule-idempotence-notest
  block:
    - name: Add cron job for regular create and prune
      cron:
        name: "borgmatic"
        hour: "{{ 6 |random }}"
        minute: "{{ 59 |random }}"
        user: "{{ borgmatic_user }}"
        cron_file: borgmatic
        job: "{{ borgmatic }} -c {{ borgmatic_config_dir }}/{{ borgmatic_config_name }} --create --prune"
    - name: Add cron job for infrequent checks
      cron:
        name: "borgmatic-check"
        day: "{{ 28 | random(seed=inventory_hostname) }}"
        hour: "{{ range(7, 24) | random(seed=inventory_hostname) }}"
        minute: "{{ 59 | random }}"
        user: "{{ borgmatic_user }}"
        cron_file: borgmatic
        job: "{{ borgmatic }} -c {{ borgmatic_config_dir }}/{{ borgmatic_config_name }} --check"
  when: borgmatic_large_repo

- name: Add cron-job for borgmatic (normal-sized repo)
  tags: molecule-idempotence-notest
  block:
    - name: Add cron job for create, check and prune
      cron:
        name: "borgmatic"
        hour: "{{ 6 | random(seed=inventory_hostname) }}"
        minute: "{{ 59 | random(seed=inventory_hostname) }}"
        user: "{{ borgmatic_user }}"
        cron_file: borgmatic
        job: "{{ borgmatic }}"
    - name: Ensure separate check cron job is absent
      cron:
        name: "borgmatic-check"
        state: absent
  when: not borgmatic_large_repo

- name: Set PATH for borgmatic cron job.
  cron:
    user: "{{ borgmatic_user }}"
    cron_file: borgmatic
    name: PATH
    env: yes
    value: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
